// Generated by GitHub Copilot
import { useState } from "react";

function TraceCard({ event }) {
    const [open, setOpen] = useState(true);

    return (
        <article
            style={{
                border: "1px solid #d0d7de",
                borderRadius: 8,
                padding: 12,
                marginBottom: 10,
            }}
        >
            <button
                type="button"
                onClick={() => setOpen((prev) => !prev)}
                style={{ background: "none", border: "none", cursor: "pointer", fontWeight: 700 }}
                aria-expanded={open}
            >
                {event.agent} {open ? "▾" : "▸"}
            </button>
            {open && (
                <pre style={{ marginTop: 10, whiteSpace: "pre-wrap", fontSize: 12 }}>
                    {JSON.stringify(event.payload, null, 2)}
                </pre>
            )}
        </article>
    );
}

export default TraceCard;
