// Generated by GitHub Copilot
import { useState } from "react";
import "./TraceCard.css";

/**
 * Return a short uppercase label for a given agent name.
 */
function getAgentTag(agent) {
    return String(agent || "agent").slice(0, 3).toUpperCase();
}

/**
 * Render one collapsible trace event card.
 */
function TraceCard({ event, index = 0 }) {
    const [open, setOpen] = useState(false);
    const delay = `${Math.min(index * 70, 700)}ms`;
    const elapsedMs = Number(event.elapsed_ms || 0).toFixed(1);

    return (
        <article className="trace-card" style={{ "--trace-delay": delay }}>
            <button
                type="button"
                onClick={() => setOpen((prev) => !prev)}
                className="trace-card-toggle"
                aria-expanded={open}
            >
                <span className="trace-card-title-wrap">
                    <span className="trace-agent-tag">{getAgentTag(event.agent)}</span>
                    <span className="trace-card-title">
                        {event.agent} / {event.stage}
                    </span>
                </span>
                <span className="trace-toggle-label">{open ? "Hide payload" : "View payload"}</span>
            </button>

            <p className="trace-message">{event.message}</p>

            <p className="trace-meta">
                <time dateTime={event.timestamp}>{event.timestamp}</time>
                <span>{elapsedMs} ms</span>
            </p>

            {open && (
                <pre className="trace-payload">
                    {JSON.stringify(event.payload, null, 2)}
                </pre>
            )}
        </article>
    );
}

export default TraceCard;
