// Generated by GitHub Copilot
import { useState } from "react";
import TraceCard from "./components/TraceCard";

const API_BASE_URL = import.meta.env.VITE_API_URL || "http://127.0.0.1:8002";

function App() {
  const [query, setQuery] = useState("");
  const [events, setEvents] = useState([]);
  const [answer, setAnswer] = useState(null);

  /**
   * Start SSE research stream and append trace steps as they arrive.
   */
  function runResearch() {
    setEvents([]);
    setAnswer(null);

    const url = `${API_BASE_URL}/research?query=${encodeURIComponent(query)}`;
    const source = new EventSource(url);

    source.addEventListener("trace", (event) => {
      const payload = JSON.parse(event.data);
      setEvents((prev) => [...prev, payload]);
    });

    source.addEventListener("answer", (event) => {
      setAnswer(JSON.parse(event.data));
      source.close();
    });

    source.onerror = () => {
      source.close();
    };
  }

  return (
    <main style={{ maxWidth: 960, margin: "24px auto", fontFamily: "Segoe UI, sans-serif" }}>
      <h1>agentic-research-assistant</h1>
      <div style={{ display: "flex", gap: 8, marginBottom: 14 }}>
        <input
          value={query}
          onChange={(event) => setQuery(event.target.value)}
          placeholder="Enter research question"
          style={{ flex: 1, padding: 10 }}
        />
        <button type="button" onClick={runResearch} disabled={!query.trim()}>
          Research
        </button>
      </div>

      <section>
        {events.map((event, index) => (
          <TraceCard key={`${event.agent}-${index}`} event={event} />
        ))}
      </section>

      {answer && (
        <section style={{ marginTop: 20 }}>
          <h2>Final Answer</h2>
          <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify(answer, null, 2)}</pre>
        </section>
      )}
    </main>
  );
}

export default App;
