// Generated by GitHub Copilot
import { useEffect, useMemo, useRef, useState } from "react";
import "./App.css";
import TraceCard from "./components/TraceCard";

const API_BASE_URL = (import.meta.env.VITE_API_URL || "http://127.0.0.1:8002").replace(/\/$/, "");
const SOURCE_OPTIONS = [3, 4, 5, 6, 7, 8];
const STYLE_OPTIONS = [
  {
    id: "corporate",
    label: "Corporate",
    hint: "Minimal, clean, and presentation-ready for stakeholder demos.",
  },
  {
    id: "futuristic",
    label: "Futuristic",
    hint: "Sharper contrast, brighter accents, and high-tech console energy.",
  },
  {
    id: "editorial",
    label: "Editorial",
    hint: "Warm surfaces, serif-forward hierarchy, and report-style readability.",
  },
];

/**
 * Return CSS class token for status pill based on current run state.
 */
function getStatusTone(status, running, errorMessage) {
  if (errorMessage || status === "Error") {
    return "status-pill--error";
  }
  if (running) {
    return "status-pill--active";
  }
  if (status.toLowerCase().includes("complete")) {
    return "status-pill--success";
  }
  return "status-pill--idle";
}

function App() {
  const streamRef = useRef(null);
  const [query, setQuery] = useState("");
  const [maxSources, setMaxSources] = useState(5);
  const [events, setEvents] = useState([]);
  const [answer, setAnswer] = useState(null);
  const [status, setStatus] = useState("Idle");
  const [errorMessage, setErrorMessage] = useState("");
  const [metadata, setMetadata] = useState(null);
  const [running, setRunning] = useState(false);
  const [styleMode, setStyleMode] = useState("corporate");

  const canRun = useMemo(() => query.trim().length >= 3 && !running, [query, running]);
  const statusTone = useMemo(() => getStatusTone(status, running, errorMessage), [status, running, errorMessage]);
  const styleMeta = useMemo(
    () => STYLE_OPTIONS.find((option) => option.id === styleMode) || STYLE_OPTIONS[0],
    [styleMode],
  );

  /**
   * Close active EventSource stream and clear reference.
   */
  function stopStream() {
    if (streamRef.current) {
      streamRef.current.close();
      streamRef.current = null;
    }
    setRunning(false);
  }

  /**
   * Open SSE stream for research workflow and append incoming trace/answer events.
   */
  function runResearch() {
    if (!canRun) {
      return;
    }

    setEvents([]);
    setAnswer(null);
    setMetadata(null);
    setErrorMessage("");
    setStatus("Starting research workflow");

    const url = `${API_BASE_URL}/research?query=${encodeURIComponent(query.trim())}&max_sources=${maxSources}`;
    const source = new EventSource(url);
    streamRef.current = source;
    setRunning(true);

    source.addEventListener("metadata", (event) => {
      setMetadata(JSON.parse(event.data));
      setStatus("Retrieving evidence");
    });

    source.addEventListener("trace", (event) => {
      const payload = JSON.parse(event.data);
      setEvents((prev) => [...prev, payload]);
      setStatus(`Running ${payload.agent} agent`);
    });

    source.addEventListener("answer", (event) => {
      setAnswer(JSON.parse(event.data));
      setStatus("Research complete");
      stopStream();
    });

    source.addEventListener("error", (event) => {
      try {
        const payload = JSON.parse(event.data);
        setErrorMessage(payload.detail || "Research workflow failed");
      } catch {
        setErrorMessage("Research workflow failed");
      }
      setStatus("Error");
      stopStream();
    });

    source.onerror = () => {
      setErrorMessage((previous) => previous || "SSE connection interrupted");
      setStatus("Connection closed");
      stopStream();
    };
  }

  useEffect(() => () => stopStream(), []);

  useEffect(() => {
    document.body.dataset.styleMode = styleMode;

    return () => {
      delete document.body.dataset.styleMode;
    };
  }, [styleMode]);

  return (
    <main className={`app-shell app-shell--${styleMode}`}>
      <div className="ambient-shape ambient-shape--one" aria-hidden="true" />
      <div className="ambient-shape ambient-shape--two" aria-hidden="true" />

      <header className="hero">
        <p className="hero-kicker">Agentic Workflow Console</p>
        <h1>Research Cockpit</h1>
        <p className="hero-copy">
          Run orchestrated Searcher, Summarizer, and Critic agents with live telemetry and source-grounded output.
        </p>

        <section className="style-switch" aria-label="Visual style preference">
          <p className="style-switch-label">Visual Mood</p>
          <div className="style-switch-buttons" role="group" aria-label="Theme selector">
            {STYLE_OPTIONS.map((option) => (
              <button
                key={option.id}
                type="button"
                className={`style-btn ${styleMode === option.id ? "style-btn--active" : ""}`}
                onClick={() => setStyleMode(option.id)}
                aria-pressed={styleMode === option.id}
              >
                {option.label}
              </button>
            ))}
          </div>
          <p className="style-switch-hint">{styleMeta.hint}</p>
        </section>

        <div className="hero-metrics" aria-label="Runtime metrics">
          <article className="metric-tile">
            <p className="metric-label">Traces</p>
            <p className="metric-value">{events.length}</p>
          </article>
          <article className="metric-tile">
            <p className="metric-label">Max Sources</p>
            <p className="metric-value">{maxSources}</p>
          </article>
          <article className="metric-tile">
            <p className="metric-label">State</p>
            <p className="metric-value">{running ? "Running" : "Ready"}</p>
          </article>
        </div>
      </header>

      <div className="layout-grid">
        <section className="panel panel--controls" aria-label="Research controls">
          <div className="panel-title-wrap">
            <h2>Run Research</h2>
            <p>Ask a focused question, then inspect trace-by-trace reasoning.</p>
          </div>

          <label className="field-label" htmlFor="query-input">
            Research Query
          </label>
          <textarea
            id="query-input"
            className="query-textarea"
            value={query}
            onChange={(event) => setQuery(event.target.value)}
            placeholder="Example: Compare modern secrets management patterns for enterprise microservices"
            rows={5}
          />

          <div className="control-row">
            <label className="field-label" htmlFor="max-sources">
              Max Sources
            </label>
            <select
              id="max-sources"
              className="source-select"
              value={maxSources}
              onChange={(event) => setMaxSources(Number(event.target.value))}
              disabled={running}
            >
              {SOURCE_OPTIONS.map((value) => (
                <option key={value} value={value}>
                  {value}
                </option>
              ))}
            </select>
          </div>

          <div className="button-row">
            <button type="button" className="btn btn--primary" onClick={runResearch} disabled={!canRun}>
              Start Research
            </button>
            <button type="button" className="btn btn--ghost" onClick={stopStream} disabled={!running}>
              Stop Stream
            </button>
          </div>

          <p className={`status-pill ${statusTone}`} aria-live="polite">
            <span className="status-dot" aria-hidden="true" />
            <span>{status}</span>
          </p>

          {metadata && (
            <p className="metadata-line">
              Request {metadata.request_id} | Started {metadata.started_at}
            </p>
          )}

          {errorMessage && (
            <p className="error-banner" role="alert">
              {errorMessage}
            </p>
          )}
        </section>

        <section className="panel panel--trace" aria-label="Trace stream">
          <div className="trace-header">
            <h2>Execution Trace</h2>
            <span className="trace-count" aria-label="Trace event count">
              {events.length}
            </span>
          </div>

          {events.length === 0 && <p className="empty-state">Run a query to stream trace events from every agent step.</p>}

          {events.map((event, index) => (
            <TraceCard key={`${event.agent}-${event.timestamp}-${index}`} event={event} index={index} />
          ))}
        </section>
      </div>

      {answer && (
        <section className="panel panel--answer" aria-label="Final answer">
          <div className="answer-header">
            <h2>Final Answer</h2>
            <p>
              {Number(answer.duration_ms).toFixed(1)} ms | {answer.trace_count} traces
            </p>
          </div>

          <h3>Summary</h3>
          <pre className="summary-block">{answer.summary}</pre>

          <h3>Critic Verdict</h3>
          <p className="verdict-line">
            <strong>{String(answer.critique?.verdict || "unknown")}</strong>
            <span> confidence {answer.critique?.confidence}</span>
          </p>

          {Array.isArray(answer.critique?.gaps) && answer.critique.gaps.length > 0 && (
            <ul className="gap-list">
              {answer.critique.gaps.map((gap) => (
                <li key={gap}>{gap}</li>
              ))}
            </ul>
          )}

          <h3>Sources</h3>
          <ul className="source-list">
            {(answer.sources || []).map((source) => (
              <li key={`${source.title}-${source.url}`}>
                <a href={source.url} target="_blank" rel="noreferrer">
                  {source.title}
                </a>
              </li>
            ))}
          </ul>
        </section>
      )}
    </main>
  );
}

export default App;
