# Generated by GitHub Copilot
"""Critic agent that checks summary quality and identifies missing evidence."""

from __future__ import annotations


def critique(summary: str) -> dict[str, object]:
    """Score summary confidence and list obvious gaps."""

    gaps: list[str] = []
    if "No sources" in summary:
        gaps.append("No supporting sources were available.")
    if len(summary) < 120:
        gaps.append("Summary is too short to be decision-grade.")

    confidence = 0.85
    if gaps:
        confidence = 0.45

    return {
        "confidence": confidence,
        "gaps": gaps,
        "verdict": "needs_revision" if gaps else "sufficient",
    }
