# Generated by GitHub Copilot
"""LangGraph StateGraph orchestration for Searcher -> Summarizer -> Critic."""

from __future__ import annotations

from typing import TypedDict

from langgraph.graph import END, StateGraph

from .critic import critique
from .searcher import search_sources
from .summarizer import summarize


class AgentState(TypedDict, total=False):
    """Shared mutable state passed between LangGraph nodes."""

    query: str
    sources: list[dict[str, str]]
    summary: str
    critique: dict[str, object]


def searcher_node(state: AgentState) -> AgentState:
    """Fetch candidate sources for the user query."""

    query = state.get("query", "")
    return {"sources": search_sources(query)}


def summarizer_node(state: AgentState) -> AgentState:
    """Generate structured summary from search evidence."""

    return {
        "summary": summarize(
            state.get("query", ""),
            state.get("sources", []),
        )
    }


def critic_node(state: AgentState) -> AgentState:
    """Evaluate the summary and assign confidence metadata."""

    return {"critique": critique(state.get("summary", ""))}


def build_graph():
    """Build and compile LangGraph workflow for research assistant."""

    graph = StateGraph(AgentState)
    graph.add_node("searcher", searcher_node)
    graph.add_node("summarizer", summarizer_node)
    graph.add_node("critic", critic_node)

    graph.set_entry_point("searcher")
    graph.add_edge("searcher", "summarizer")
    graph.add_edge("summarizer", "critic")
    graph.add_edge("critic", END)

    return graph.compile()
