# Generated by GitHub Copilot
"""Searcher agent that retrieves grounded web evidence via Tavily."""

from __future__ import annotations

import os
import requests


def search_sources(query: str, limit: int = 5) -> list[dict[str, str]]:
    """Return top web sources for a query using Tavily search API."""

    api_key = os.getenv("TAVILY_API_KEY", "")
    if not api_key:
        return [
            {
                "title": "Missing Tavily key",
                "url": "https://example.com/setup",
                "content": "Set TAVILY_API_KEY to enable live web search.",
            }
        ]

    response = requests.post(
        "https://api.tavily.com/search",
        json={"api_key": api_key, "query": query, "max_results": limit},
        timeout=15,
    )
    response.raise_for_status()
    payload = response.json()

    results = payload.get("results", [])
    return [
        {
            "title": item.get("title", "Untitled"),
            "url": item.get("url", ""),
            "content": item.get("content", ""),
        }
        for item in results[:limit]
    ]
