# Generated by GitHub Copilot
"""Summarizer agent that builds structured brief from evidence."""

from __future__ import annotations


def summarize(query: str, sources: list[dict[str, str]]) -> str:
    """Create a concise research brief from retrieved sources."""

    if not sources:
        return "No sources were retrieved for this query."

    bullets = []
    for item in sources[:5]:
        title = item.get("title", "Untitled")
        content = item.get("content", "")[:240]
        bullets.append(f"- {title}: {content}")

    return f"Research brief for '{query}':\n" + "\n".join(bullets)
