# Generated by GitHub Copilot
"""Deterministic evaluation harness for research quality and citation faithfulness."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from datetime import datetime, timezone
import json
import os
from pathlib import Path
import random
import re
import sys
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from agents.graph import build_graph, resolve_execution_budget, run_research


@dataclass(frozen=True)
class EvalScenario:
    """Represents one deterministic evaluation scenario and pass thresholds."""

    scenario_id: str
    seed: int
    query: str
    max_sources: int
    execution_tier: str
    expected_verdict: str
    expected_min_confidence: float
    expected_min_citation_match: float


# Generated by GitHub Copilot
def build_parser() -> argparse.ArgumentParser:
    """Build and return CLI parser for the evaluation harness."""

    parser = argparse.ArgumentParser(description="Evaluate deterministic quality and citation faithfulness")
    parser.add_argument(
        "--scenario-file",
        default="eval/scenarios/deterministic_eval.json",
        help="Path to deterministic scenario JSON file",
    )
    parser.add_argument(
        "--output-json",
        default="eval/results/deterministic_eval_results.json",
        help="Path to write JSON evaluation summary",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Global random seed override for deterministic runs",
    )
    return parser


# Generated by GitHub Copilot
def parse_reference_urls(summary: str) -> set[str]:
    """Extract URLs from summary references for citation-faithfulness scoring."""

    return set(re.findall(r"https?://[^\s]+", summary))


# Generated by GitHub Copilot
def load_scenarios(path: Path) -> list[EvalScenario]:
    """Load and validate deterministic scenarios from JSON file."""

    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, list) or not payload:
        raise ValueError("scenario file must contain a non-empty JSON array")

    scenarios: list[EvalScenario] = []
    for item in payload:
        scenarios.append(
            EvalScenario(
                scenario_id=str(item["id"]),
                seed=int(item.get("seed", 42)),
                query=str(item["query"]),
                max_sources=int(item["max_sources"]),
                execution_tier=str(item["execution_tier"]),
                expected_verdict=str(item["expected_verdict"]),
                expected_min_confidence=float(item["expected_min_confidence"]),
                expected_min_citation_match=float(item["expected_min_citation_match"]),
            )
        )

    return scenarios


# Generated by GitHub Copilot
def evaluate_scenario(scenario: EvalScenario, compiled_graph) -> dict[str, Any]:
    """Execute one scenario and return pass-fail breakdown with metrics."""

    random.seed(scenario.seed)
    execution_tier, source_budget = resolve_execution_budget(
        max_sources=scenario.max_sources,
        execution_tier=scenario.execution_tier,
    )

    result = run_research(
        query=scenario.query,
        max_sources=source_budget,
        compiled_graph=compiled_graph,
        execution_tier=execution_tier,
    )

    summary_text = str(result["summary"])
    source_urls = [str(item.get("url", "")).strip() for item in result["sources"] if item.get("url")]
    cited_urls = parse_reference_urls(summary_text)

    matched_citations = sum(1 for url in source_urls if url in cited_urls)
    citation_match_ratio = (matched_citations / len(source_urls)) if source_urls else 0.0

    confidence = float(result["critique"].get("confidence", 0.0))
    verdict = str(result["critique"].get("verdict", "unknown"))

    checks = {
        "verdict_ok": verdict == scenario.expected_verdict,
        "confidence_ok": confidence >= scenario.expected_min_confidence,
        "citation_match_ok": citation_match_ratio >= scenario.expected_min_citation_match,
    }

    return {
        "scenario_id": scenario.scenario_id,
        "query": scenario.query,
        "execution_tier": execution_tier,
        "source_budget": source_budget,
        "source_count": len(source_urls),
        "duration_ms": float(result["duration_ms"]),
        "verdict": verdict,
        "confidence": round(confidence, 4),
        "citation_match_ratio": round(citation_match_ratio, 4),
        "checks": checks,
        "passed": all(checks.values()),
    }


# Generated by GitHub Copilot
def render_markdown_table(rows: list[dict[str, Any]]) -> str:
    """Render evaluation outcomes as a compact markdown table."""

    lines = [
        "| Scenario | Tier | Verdict | Confidence | Citation Match | Passed |",
        "| --- | --- | --- | ---: | ---: | --- |",
    ]

    for row in rows:
        lines.append(
            "| {scenario_id} | {execution_tier} | {verdict} | {confidence} | {citation_match_ratio} | {passed} |".format(
                scenario_id=row["scenario_id"],
                execution_tier=row["execution_tier"],
                verdict=row["verdict"],
                confidence=row["confidence"],
                citation_match_ratio=row["citation_match_ratio"],
                passed="yes" if row["passed"] else "no",
            )
        )

    return "\n".join(lines)


# Generated by GitHub Copilot
def main() -> int:
    """Run deterministic evaluation scenarios and write JSON result summary."""

    args = build_parser().parse_args()

    scenario_file = Path(args.scenario_file)
    output_json = Path(args.output_json)

    if not scenario_file.exists():
        raise FileNotFoundError(f"Scenario file not found: {scenario_file}")

    random.seed(args.seed)
    os.environ.pop("TAVILY_API_KEY", None)

    scenarios = load_scenarios(scenario_file)
    graph = build_graph()

    rows = [evaluate_scenario(item, compiled_graph=graph) for item in scenarios]

    passed_count = sum(1 for row in rows if row["passed"])
    summary = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "scenario_file": str(scenario_file),
        "total_scenarios": len(rows),
        "passed_scenarios": passed_count,
        "failed_scenarios": len(rows) - passed_count,
        "pass_rate": round(passed_count / len(rows), 4),
        "results": rows,
    }

    output_json.parent.mkdir(parents=True, exist_ok=True)
    output_json.write_text(json.dumps(summary, indent=2), encoding="utf-8")

    print(render_markdown_table(rows))
    print("\nEvaluation summary:")
    print(json.dumps({k: summary[k] for k in ["total_scenarios", "passed_scenarios", "failed_scenarios", "pass_rate"]}, indent=2))
    print(f"\nWrote JSON results to: {output_json}")

    return 0 if summary["failed_scenarios"] == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
