
"""FastAPI API exposing a streaming research endpoint over SSE."""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass
from datetime import datetime, timezone
import json
import os
import re
from threading import Lock
from time import perf_counter
from typing import Annotated
from uuid import uuid4

from fastapi import Depends, FastAPI, Header, HTTPException, Query, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.middleware.gzip import GZipMiddleware
from fastapi.responses import JSONResponse, PlainTextResponse
from prometheus_client import CONTENT_TYPE_LATEST, Counter, Histogram, generate_latest
from pydantic import BaseModel, Field
from sse_starlette.sse import EventSourceResponse
from starlette.middleware.trustedhost import TrustedHostMiddleware

from agents.graph import build_graph, run_research, stream_research


@dataclass(frozen=True)
class Settings:
    """Runtime settings for API security controls and execution defaults."""

    app_name: str
    app_version: str
    environment: str
    cors_origins: list[str]
    allowed_hosts: list[str]
    rate_limit_per_minute: int
    max_query_length: int
    default_max_sources: int
    api_key: str
    enforce_api_key_in_production: bool
    enable_hsts: bool


class InMemoryRateLimiter:
    """Sliding-window limiter used to protect research endpoints from abuse."""

    def __init__(self, window_seconds: int = 60) -> None:
        """Initialize in-memory limiter state."""

        self._window_seconds = window_seconds
        self._store: dict[str, deque[float]] = {}
        self._lock = Lock()

    def allow(self, key: str, limit: int) -> bool:
        """Return True when current request is within configured rate limit."""

        now = perf_counter()
        with self._lock:
            queue = self._store.setdefault(key, deque())
            cutoff = now - self._window_seconds
            while queue and queue[0] < cutoff:
                queue.popleft()
            if len(queue) >= limit:
                return False
            queue.append(now)
        return True

    def clear(self) -> None:
        """Reset in-memory limiter state for deterministic tests."""

        with self._lock:
            self._store.clear()


class HealthResponse(BaseModel):
    """Health payload used by uptime checks and runtime diagnostics."""

    status: str
    timestamp: str
    app_version: str
    environment: str
    rate_limit_per_minute: int
    max_query_length: int


class ResearchRequest(BaseModel):
    """Request body for synchronous research execution endpoint."""

    query: str = Field(min_length=3, max_length=800)
    max_sources: int = Field(default=5, ge=1, le=8)


class ResearchAnswer(BaseModel):
    """Normalized final answer payload returned by research endpoints."""

    query: str
    summary: str
    critique: dict[str, object]
    sources: list[dict[str, str]]
    trace: list[dict[str, object]]
    trace_count: int
    duration_ms: float
    request_id: str


# Generated by GitHub Copilot
def _parse_bool(raw_value: str | None, default: bool) -> bool:
    """Parse environment-backed boolean values with resilient defaults."""

    if raw_value is None:
        return default
    normalized = raw_value.strip().lower()
    if normalized in {"1", "true", "yes", "on"}:
        return True
    if normalized in {"0", "false", "no", "off"}:
        return False
    return default


# Generated by GitHub Copilot
def _is_production_env(environment: str) -> bool:
    """Return True when runtime environment should enforce production safeguards."""

    return environment.strip().lower() in {"prod", "production"}


# Generated by GitHub Copilot
def _validate_settings(runtime_settings: Settings) -> None:
    """Fail fast when runtime configuration is unsafe or invalid."""

    if runtime_settings.rate_limit_per_minute <= 0:
        raise RuntimeError("RATE_LIMIT_PER_MINUTE must be greater than 0")
    if runtime_settings.max_query_length < 64:
        raise RuntimeError("MAX_QUERY_LENGTH must be at least 64")
    if runtime_settings.default_max_sources < 1 or runtime_settings.default_max_sources > 8:
        raise RuntimeError("DEFAULT_MAX_SOURCES must be between 1 and 8")
    if not runtime_settings.cors_origins:
        raise RuntimeError("CORS_ORIGINS must include at least one origin")
    if not runtime_settings.allowed_hosts:
        raise RuntimeError("ALLOWED_HOSTS must include at least one host")

    if _is_production_env(runtime_settings.environment):
        if runtime_settings.enforce_api_key_in_production and not runtime_settings.api_key:
            raise RuntimeError("RESEARCH_API_KEY must be set when APP_ENV is production")
        if "*" in runtime_settings.cors_origins:
            raise RuntimeError("CORS_ORIGINS cannot include wildcard '*' when APP_ENV is production")
        if "*" in runtime_settings.allowed_hosts:
            raise RuntimeError("ALLOWED_HOSTS cannot include wildcard '*' when APP_ENV is production")


def _load_settings() -> Settings:
    """Read runtime settings from environment with safe defaults."""

    origins = os.getenv("CORS_ORIGINS", "http://127.0.0.1:4175,http://localhost:4175")
    allowed_hosts = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost,testserver,api,frontend")
    return Settings(
        app_name=os.getenv("APP_NAME", "agentic-research-assistant"),
        app_version=os.getenv("APP_VERSION", "0.2.0"),
        environment=os.getenv("APP_ENV", "development"),
        cors_origins=[origin.strip() for origin in origins.split(",") if origin.strip()],
        allowed_hosts=[host.strip() for host in allowed_hosts.split(",") if host.strip()],
        rate_limit_per_minute=int(os.getenv("RATE_LIMIT_PER_MINUTE", "90")),
        max_query_length=int(os.getenv("MAX_QUERY_LENGTH", "800")),
        default_max_sources=int(os.getenv("DEFAULT_MAX_SOURCES", "5")),
        api_key=os.getenv("RESEARCH_API_KEY", "").strip(),
        enforce_api_key_in_production=_parse_bool(os.getenv("ENFORCE_API_KEY_IN_PRODUCTION"), default=True),
        enable_hsts=_parse_bool(os.getenv("ENABLE_HSTS"), default=False),
    )


def _require_api_key(
    x_api_key: Annotated[str | None, Header(alias="X-API-Key")] = None,
) -> None:
    """Enforce optional API key auth for protected research endpoints."""

    if not settings.api_key:
        return
    if x_api_key != settings.api_key:
        raise HTTPException(status_code=401, detail="Unauthorized")


def _guard_query(query: str, max_query_length: int) -> str:
    """Validate and sanitize user query for safe agent execution."""

    sanitized = re.sub(r"\s+", " ", query).strip()
    if len(sanitized) < 3:
        raise HTTPException(status_code=422, detail="Query must contain at least 3 characters")
    if len(sanitized) > max_query_length:
        raise HTTPException(status_code=422, detail=f"Query exceeds max length {max_query_length}")

    blocked_patterns = [r"ignore\s+previous\s+instructions", r"system\s+prompt", r"bypass\s+guardrails"]
    if any(re.search(pattern, sanitized, flags=re.IGNORECASE) for pattern in blocked_patterns):
        raise HTTPException(status_code=400, detail="Query contains disallowed instruction pattern")

    return sanitized


def _request_key(request: Request) -> str:
    """Build a rate-limit key from request client information."""

    return request.client.host if request.client else "unknown"


settings = _load_settings()
_validate_settings(settings)
compiled_graph = build_graph()
limiter = InMemoryRateLimiter(window_seconds=60)
AuthDep = Annotated[None, Depends(_require_api_key)]

REQUEST_COUNTER = Counter(
    "research_api_requests_total",
    "Research API request count",
    labelnames=("method", "endpoint", "status"),
)
REQUEST_LATENCY = Histogram(
    "research_api_request_duration_seconds",
    "Research API request duration in seconds",
    labelnames=("method", "endpoint"),
    buckets=(0.05, 0.1, 0.25, 0.5, 1.0, 2.0, 5.0),
)

app = FastAPI(title=settings.app_name, version=settings.app_version)
app.add_middleware(
    TrustedHostMiddleware,
    allowed_hosts=settings.allowed_hosts,
)
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins,
    allow_credentials=False,
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)
app.add_middleware(GZipMiddleware, minimum_size=512)


@app.middleware("http")
async def request_context_middleware(request: Request, call_next):
    """Attach security headers, request id, and request-level metrics."""

    request_id = request.headers.get("X-Request-ID", str(uuid4()))
    request.state.request_id = request_id
    started_at = perf_counter()

    response = await call_next(request)

    REQUEST_COUNTER.labels(
        method=request.method,
        endpoint=request.url.path,
        status=str(response.status_code),
    ).inc()
    REQUEST_LATENCY.labels(method=request.method, endpoint=request.url.path).observe(perf_counter() - started_at)

    response.headers["X-Request-ID"] = request_id
    response.headers["X-Content-Type-Options"] = "nosniff"
    response.headers["X-Frame-Options"] = "DENY"
    response.headers["Referrer-Policy"] = "strict-origin-when-cross-origin"
    response.headers["Permissions-Policy"] = "camera=(), microphone=()"
    response.headers["Content-Security-Policy"] = "default-src 'none'; frame-ancestors 'none'; base-uri 'none'"
    if settings.enable_hsts:
        response.headers["Strict-Transport-Security"] = "max-age=31536000; includeSubDomains"
    return response


@app.exception_handler(HTTPException)
async def http_exception_handler(request: Request, exc: HTTPException) -> JSONResponse:
    """Return structured API errors including request id for debugging."""

    return JSONResponse(
        status_code=exc.status_code,
        content={
            "detail": str(exc.detail),
            "request_id": getattr(request.state, "request_id", None),
        },
    )


@app.get("/health")
def health() -> HealthResponse:
    """Return service health for monitoring and deployment checks."""

    return HealthResponse(
        status="ok",
        timestamp=datetime.now(timezone.utc).isoformat(),
        app_version=settings.app_version,
        environment=settings.environment,
        rate_limit_per_minute=settings.rate_limit_per_minute,
        max_query_length=settings.max_query_length,
    )


@app.post("/research/run", response_model=ResearchAnswer)
def research_run(request: Request, payload: ResearchRequest, _: AuthDep = None) -> ResearchAnswer:
    """Run research workflow synchronously for automation and integration tests."""

    if not limiter.allow(_request_key(request), settings.rate_limit_per_minute):
        raise HTTPException(status_code=429, detail="Rate limit exceeded")

    query = _guard_query(payload.query, settings.max_query_length)
    result = run_research(query=query, max_sources=payload.max_sources, compiled_graph=compiled_graph)
    request_id = str(request.state.request_id)
    return ResearchAnswer(
        query=result["query"],
        summary=result["summary"],
        critique=result["critique"],
        sources=result["sources"],
        trace=result["trace"],
        trace_count=len(result["trace"]),
        duration_ms=float(result["duration_ms"]),
        request_id=request_id,
    )


@app.get("/research")
def research(
    request: Request,
    _: AuthDep = None,
    query: str = Query(..., min_length=3, max_length=800),
    max_sources: int = Query(default=settings.default_max_sources, ge=1, le=8),
) -> EventSourceResponse:
    """Stream agent-by-agent execution trace and final answer for a query."""

    if not limiter.allow(_request_key(request), settings.rate_limit_per_minute):
        raise HTTPException(status_code=429, detail="Rate limit exceeded")

    sanitized_query = _guard_query(query, settings.max_query_length)
    request_id = str(request.state.request_id)

    async def event_generator():
        yield {
            "event": "metadata",
            "data": json.dumps(
                {
                    "request_id": request_id,
                    "query": sanitized_query,
                    "started_at": datetime.now(timezone.utc).isoformat(),
                },
                ensure_ascii=True,
            ),
        }

        try:
            for item in stream_research(sanitized_query, max_sources=max_sources, compiled_graph=compiled_graph):
                if item["type"] == "trace":
                    payload = dict(item["payload"])
                    payload["request_id"] = request_id
                    yield {
                        "event": "trace",
                        "data": json.dumps(payload, ensure_ascii=True),
                    }
                    continue

                answer = dict(item["payload"])
                answer["request_id"] = request_id
                answer["trace_count"] = len(answer.get("trace", []))
                yield {
                    "event": "answer",
                    "data": json.dumps(answer, ensure_ascii=True),
                }
        except Exception as exc:  # pragma: no cover
            yield {
                "event": "error",
                "data": json.dumps(
                    {
                        "request_id": request_id,
                        "detail": f"Research workflow failed: {exc}",
                    },
                    ensure_ascii=True,
                ),
            }

    return EventSourceResponse(event_generator())


@app.get("/metrics")
def metrics() -> PlainTextResponse:
    """Expose Prometheus metrics for API and workflow monitoring."""

    return PlainTextResponse(generate_latest(), media_type=CONTENT_TYPE_LATEST)
