# Generated by GitHub Copilot
"""FastAPI API exposing a streaming research endpoint over SSE."""

from __future__ import annotations

import json
from fastapi import FastAPI, Query
from sse_starlette.sse import EventSourceResponse

from agents.graph import build_graph

app = FastAPI(title="agentic-research-assistant", version="0.1.0")
compiled_graph = build_graph()


@app.get("/health")
def health() -> dict[str, str]:
    """Return service health for monitoring and deployment checks."""

    return {"status": "ok"}


@app.get("/research")
def research(query: str = Query(..., min_length=3)) -> EventSourceResponse:
    """Stream agent-by-agent execution trace and final answer for a query."""

    async def event_generator():
        state = {"query": query}
        for step in compiled_graph.stream(state):
            for agent_name, payload in step.items():
                yield {
                    "event": "trace",
                    "data": json.dumps({"agent": agent_name, "payload": payload}),
                }

        final = compiled_graph.invoke(state)
        yield {
            "event": "answer",
            "data": json.dumps(
                {
                    "query": query,
                    "summary": final.get("summary", ""),
                    "critique": final.get("critique", {}),
                    "sources": final.get("sources", []),
                }
            ),
        }

    return EventSourceResponse(event_generator())
